 version: '3.1'
name: hibernate-final
services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - C:\MyDockerVolume:mysql:var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - mysql